In [1]:
import numpy as np
import time
import gymnasium as gym
import random
import torch
from collections import namedtuple, Counter
import matplotlib.pyplot as plt
import os
import sys
SCRIPT_DIR = os.path.dirname(os.path.abspath("..src"))
sys.path.append(os.path.dirname(SCRIPT_DIR))

In [2]:
from src.wrappers.env_wrappers import ChannelsObs, StochasticAction, TimeStepReward, WindowViewObs, WallObs
from src.wrappers.monitor_wrappers import BinaryMonitor

In [3]:
seed = 0
gamma = 0.99
window_size = 5
grid_size = (9, 9)
env = gym.make("gym_monitor/TreasureHunt-Penalty-v1", render_modes="human", seed=seed)
env = ChannelsObs(env, grid_size=grid_size, n_objects=3)
env = WallObs(env, grid_size=grid_size, n_walls=2)
env = WindowViewObs(env, window_size=window_size)
# env = TimeStepReward(env, timestep_penalty=0.0, goal_reward=1, fire_reward=-10)
# env = BinaryMonitor(env, full_monitor=False, monitor_cost=0.2, init_monitor_state=0.0, monitor_reset_prob=0.0)

In [5]:
n_episodes = 1
for i in range(n_episodes):
    s, _ = env.reset()
    total_r, timestep = 0, 0
    done = False
    actions = 16 * [1, 2]
    while not done and timestep < 20:
        print(s[0, :, :], "\n")
        action = actions[timestep] #2 #env.action_space.sample()
        s, r, done, _, info = env.step(action)
        # s, r, done, _, info = env.step({"mdp": action % 4, "monitor": action // 4})
        # reward = info["mdp_reward"] + r["monitor"]
        # total_r += reward * (gamma ** timestep)
        timestep += 1

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.

In [10]:
s[3]

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
# s, _ = env.reset()
new_s = s.reshape(9,9)
print("obs\n", new_s)
pos_x, pos_y = np.where(new_s == 1)[0][0], np.where(new_s == 1)[1][0]
print("pos", pos_x, pos_y)
min_x, max_x = max(0, pos_x - window_size[0] // 2), min(grid_size[0], pos_x + window_size[0] // 2 + 1)
min_y, max_y = max(0, pos_y - window_size[1] // 2), min(grid_size[1], pos_y + window_size[0] // 2 + 1)
print("x", min_x, max_x)
print("y", min_y, max_y)

print(new_s[min_x: max_x, min_y: max_y])

ValueError: cannot reshape array of size 484 into shape (9,9)